export const countries = [
  { code: "AG", name: "Antigua y Barbuda", flag: "🇦🇬" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸" },
  { code: "BB", name: "Barbados", flag: "🇧🇧" },
  { code: "BZ", name: "Belice", flag: "🇧🇿" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "DM", name: "Dominica", flag: "🇩🇲" },
  { code: "DO", name: "República Dominicana", flag: "🇩🇴" },
  { code: "GD", name: "Granada", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "HT", name: "Haití", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲" },
  { code: "MX", name: "México", flag: "🇲🇽" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "PA", name: "Panamá", flag: "🇵🇦" },
  { code: "KN", name: "San Cristóbal y Nieves", flag: "🇰🇳" },
  { code: "LC", name: "Santa Lucía", flag: "🇱🇨" },
  { code: "VC", name: "San Vicente y las Granadinas", flag: "🇻🇨" },
  { code: "TT", name: "Trinidad y Tobago", flag: "🇹🇹" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "CA", name: "Canadá", flag: "🇨🇦" },
];
